num1 = float(input("Enter 1st Num: "))
num2 = float(input("Enter 2nd Num: "))
num3 = float(input("Enter 3rd Num: "))
max_num = max(num1, num2, num3)
print("The maximum of the three numbers is", max_num)